version: "3"
services:
  # -----------------------------------------------
  # ------------------ FRONTEND -------------------
  # -----------------------------------------------
  frontend:
    container_name: task-ci-cd-frontend
    build:
      context: ./frontend
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
      # Don't include node_modules in volume.
      # When adding a dependency, the image has to be built again or we have to go into the container and install the dependency manually
      - /frontend/node_modules/
    ports:
      - 5173:5173
    restart: always

  # -----------------------------------------------
  # ------------------- BACKEND -------------------
  # -----------------------------------------------
  backend:
    container_name: task-ci-cd-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/backend
      # Don't include node_modules in volume.
      # When adding a dependency, the image has to be built again or we have to go into the container and install the dependency manually
      - /backend/node_modules/
    ports:
      - 3333:3333
    restart: always

  # -----------------------------------------------
  # ------------------- JENKINS -------------------
  # -----------------------------------------------
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: admin
  #   ports:
  #     - 8080:8080
  #     - 50000:50000
  #   container_name: jenkins
  #   restart: always
