pipeline {
    agent any
    
    stages {
        stage('Prettier') {
            steps {
                dir('backend') {
                    sh 'pnpm install'
                    sh 'pnpm run prettier:check'
                }
            }
        }
        stage('ESLint') {
            steps {
                dir('backend') {
                    sh 'pnpm install'
                    sh 'pnpm run lint'
                }
            }
        }
        stage('Build') {
            steps {
                dir('backend') {
                    sh 'pnpm install'
                    sh 'pnpm run build'
                }
            }
        }
        stage('Tests') {
            steps {
                dir('backend') {
                    sh 'pnpm install'
                    sh 'pnpm t'
                }
            }
        }
    }
}
